'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class CorporateEntities
    Inherits DbContext

	' Added by Tim to AllData.Context.tt file
	Public Sub New(connectionString As String)
        MyBase.New(connectionString)
    End Sub

    Public Sub New()
        MyBase.New("name=CorporateEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property CustomerOrders() As DbSet(Of CustomerOrder)
    Public Overridable Property Customers() As DbSet(Of Customer)
    Public Overridable Property CustomOrderAddresses() As DbSet(Of CustomOrderAddress)
    Public Overridable Property CustOrderDetails() As DbSet(Of CustOrderDetail)
    Public Overridable Property CustOrderItemDetails() As DbSet(Of CustOrderItemDetail)
    Public Overridable Property Errors() As DbSet(Of [Error])
    Public Overridable Property InvoiceDetails() As DbSet(Of InvoiceDetail)
    Public Overridable Property Invoices() As DbSet(Of Invoice)
    Public Overridable Property Items() As DbSet(Of Item)
    Public Overridable Property MachineItems() As DbSet(Of MachineItem)
    Public Overridable Property Machines() As DbSet(Of Machine)
    Public Overridable Property OrderDetails() As DbSet(Of OrderDetail)
    Public Overridable Property Orders() As DbSet(Of Order)
    Public Overridable Property Parts() As DbSet(Of Part)
    Public Overridable Property Spare_Parts() As DbSet(Of Spare_Part)
    Public Overridable Property Suppliers() As DbSet(Of Supplier)
    Public Overridable Property Quotes() As DbSet(Of Quote)
    Public Overridable Property QuoteDetails() As DbSet(Of QuoteDetail)
    Public Overridable Property QuoteItemDetails() As DbSet(Of QuoteItemDetail)
    Public Overridable Property FlatOrders() As DbSet(Of FlatOrder)

End Class
