'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CustOrderDetail
    Public Property ID As Integer
    Public Property OrderID As Integer
    Public Property ItemID As Nullable(Of Integer)
    Public Property Description As String
    Public Property Unit As String
    Public Property Price As Nullable(Of Decimal)
    Public Property Quantity As Nullable(Of Decimal)
    Public Property DiscountFraction As Nullable(Of Decimal)

    Public Overridable Property CustomerOrder As CustomerOrder
    Public Overridable Property Item As Item
    Public Overridable Property CustOrderItemDetails As ObservableListSource(Of CustOrderItemDetail) = New ObservableListSource(Of CustOrderItemDetail)
    Public Overridable Property InvoiceDetails As ObservableListSource(Of InvoiceDetail) = New ObservableListSource(Of InvoiceDetail)
    Public Overridable Property Machines As ObservableListSource(Of Machine) = New ObservableListSource(Of Machine)

End Class
