'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CustomerOrder
    Public Property ID As Integer
    Public Property CustomerID As Nullable(Of Integer)
    Public Property OrderRef As String
    Public Property [Date] As Nullable(Of Date)
    Public Property Currency As String
    Public Property Carrier As String
    Public Property Notes As String
    Public Property DespatchDate As Nullable(Of Date)
    Public Property InvoiceID As Nullable(Of Integer)
    Public Property DiscountFraction As Nullable(Of Decimal)
    Public Property ParentOrder As Nullable(Of Integer)

    Public Overridable Property Customer As Customer
    Public Overridable Property CustOrderDetails As ObservableListSource(Of CustOrderDetail) = New ObservableListSource(Of CustOrderDetail)
    Public Overridable Property Invoice As Invoice
    Public Overridable Property CustomerOrders1 As ObservableListSource(Of CustomerOrder) = New ObservableListSource(Of CustomerOrder)
    Public Overridable Property CustomerOrder1 As CustomerOrder

End Class
