'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CustomOrderAddress
    Public Property Entry As Integer
    Public Property OrderNo As Integer
    Public Property Supplier As String
    Public Property FaxNumber As String
    Public Property Address1 As String
    Public Property Address2 As String
    Public Property Address3 As String
    Public Property Address4 As String
    Public Property Postcode As String

    Public Overridable Property Order As Order

End Class
