'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Customer
    Public Property ID As Integer
    Public Property Company As String
    Public Property Contact As String
    Public Property Telephone As String
    Public Property Fax As String
    Public Property Email As String
    Public Property Address_1 As String
    Public Property Address_2 As String
    Public Property Address_3 As String
    Public Property Region As String
    Public Property Post_code As String
    Public Property Country As String
    Public Property Last_contact As Nullable(Of Date)
    Public Property Contact_regularity As String
    Public Property Notes As String
    Public Property DefaultCurrency As String
    Public Property Archived As Boolean
    Public Property VatNo As String

    Public Overridable Property CustomerOrders As ObservableListSource(Of CustomerOrder) = New ObservableListSource(Of CustomerOrder)
    Public Overridable Property Invoices As ObservableListSource(Of Invoice) = New ObservableListSource(Of Invoice)
    Public Overridable Property Machines As ObservableListSource(Of Machine) = New ObservableListSource(Of Machine)
    Public Overridable Property Quotes As ObservableListSource(Of Quote) = New ObservableListSource(Of Quote)

End Class
