'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CustOrderItemDetail
    Public Property ID As Integer
    Public Property DetailID As Integer
    Public Property ItemID As Nullable(Of Integer)
    Public Property Description As String
    Public Property Quantity As Nullable(Of Decimal)
    Public Property Status As String
    Public Property ParentID As Nullable(Of Integer)

    Public Overridable Property CustOrderDetail As CustOrderDetail
    Public Overridable Property Item As Item
    Public Overridable Property Children As ObservableListSource(Of CustOrderItemDetail) = New ObservableListSource(Of CustOrderItemDetail)
    Public Overridable Property Parent As CustOrderItemDetail

End Class
