'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class FlatOrder
    Public Property ID As Integer
    Public Property Order As Integer
    Public Property RowNo As Integer
    Public Property Qty As Nullable(Of Single)
    Public Property Unit As String
    Public Property Part As String
    Public Property Description As String
    Public Property UnitPrice As Nullable(Of Decimal)
    Public Property Price As Nullable(Of Decimal)
    Public Property RowNotes As String
    Public Property RowRecieved As Boolean
    Public Property Inspected As Boolean
    Public Property [Date] As Nullable(Of Date)
    Public Property Suffix As String
    Public Property StartText As String
    Public Property EndText As String
    Public Property Notes As String
    Public Property Due As Nullable(Of Date)
    Public Property Sent As Boolean
    Public Property Received As Boolean
    Public Property Supplier As String
    Public Property Address1 As String
    Public Property Address2 As String
    Public Property Address3 As String
    Public Property Address4 As String
    Public Property Postcode As String

End Class
