'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Invoice
    Public Property ID As Integer
    Public Property CustomerID As Nullable(Of Integer)
    Public Property CustomerRef As String
    Public Property [Date] As Nullable(Of Date)
    Public Property StartText As String
    Public Property CarriageText As String
    Public Property CarriageCost As Nullable(Of Decimal)
    Public Property Currency As String
    Public Property GBPEquiv As Nullable(Of Decimal)
    Public Property SignedFaoBo As String
    Public Property Notes As String
    Public Property DueDate As Nullable(Of Date)
    Public Property RemittanceDetails As String
    Public Property PackageDetails As String
    Public Property VatFraction As Nullable(Of Decimal)

    Public Overridable Property Customer As Customer
    Public Overridable Property InvoiceDetails As ICollection(Of InvoiceDetail) = New HashSet(Of InvoiceDetail)
    Public Overridable Property CustomerOrders As ICollection(Of CustomerOrder) = New HashSet(Of CustomerOrder)

End Class
