'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class InvoiceDetail
    Public Property ID As Integer
    Public Property InvoiceID As Integer
    Public Property DetailID As Nullable(Of Integer)
    Public Property RowNo As Integer
    Public Property ExtraText As String

    Public Overridable Property CustOrderDetail As CustOrderDetail
    Public Overridable Property Invoice As Invoice

End Class
