'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Item
    Public Property ID As Integer
    Public Property Type As String
    Public Property PartID As Integer
    Public Property Model As String
    Public Property Item1 As String
    Public Property Description As String
    Public Property Qty As Nullable(Of Decimal)
    Public Property Status As String
    Public Property Associations As String
    Public Property Exclude As Boolean
    Public Property ParentID As Nullable(Of Integer)

    Public Overridable Property CustOrderDetails As ICollection(Of CustOrderDetail) = New HashSet(Of CustOrderDetail)
    Public Overridable Property CustOrderItemDetails As ICollection(Of CustOrderItemDetail) = New HashSet(Of CustOrderItemDetail)
    Public Overridable Property Part As Part
    Public Overridable Property MachineItems As ICollection(Of MachineItem) = New HashSet(Of MachineItem)
    Public Overridable Property QuoteDetails As ICollection(Of QuoteDetail) = New HashSet(Of QuoteDetail)
    Public Overridable Property QuoteItemDetails As ICollection(Of QuoteItemDetail) = New HashSet(Of QuoteItemDetail)
    Public Overridable Property Children As ICollection(Of Item) = New HashSet(Of Item)
    Public Overridable Property Parent As Item

End Class
