'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OperationType
    Public Property ID As Integer
    Public Property Description As String

    Public Overridable Property Parts As ICollection(Of Part) = New HashSet(Of Part)
    Public Overridable Property Suppliers As ICollection(Of Supplier) = New HashSet(Of Supplier)

End Class
