'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Order
    Public Property OrderNo As Integer
    Public Property Supplier As Nullable(Of Integer)
    Public Property [Date] As Nullable(Of Date)
    Public Property Suffix As String
    Public Property StartText As String
    Public Property EndText As String
    Public Property Notes As String
    Public Property Due As Nullable(Of Date)
    Public Property Received As Boolean
    Public Property Sent As Boolean

    Public Overridable Property CustomOrderAddresses As ObservableListSource(Of CustomOrderAddress) = New ObservableListSource(Of CustomOrderAddress)
    Public Overridable Property Errors As ObservableListSource(Of [Error]) = New ObservableListSource(Of [Error])
    Public Overridable Property OrderDetails As ObservableListSource(Of OrderDetail) = New ObservableListSource(Of OrderDetail)
    Public Overridable Property Supplier1 As Supplier

End Class
