'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OrderDetail
    Public Property ID As Integer
    Public Property Order As Integer
    Public Property RowNo As Integer
    Public Property Qty As Nullable(Of Single)
    Public Property Unit As String
    Public Property Part As Nullable(Of Integer)
    Public Property Description As String
    Private Property oUnitPrice As Nullable(Of Decimal)
    Private Property oPrice As Nullable(Of Decimal)
    Public Property RowNotes As String
    Public Property Received As Boolean
    Public Property Inspected As Boolean

    Public Overridable Property Order1 As Order
    Public Overridable Property Part1 As Part

End Class
