'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Part
    Public Property ID As Integer
    Public Property Stock As Nullable(Of Decimal)
    Public Property PartNo As String
    Public Property DrawingType As String
    Public Property Description As String
    Public Property Supplier As String
    Public Property SuppliersDescription As String
    Public Property ProductionNotes As String
    Public Property Status As String
    Public Property Unit As Nullable(Of Decimal)
    Public Property SecondOperation As Nullable(Of Decimal)
    Public Property DateChecked As Nullable(Of Date)
    Public Property Nett As Nullable(Of Decimal)
    Public Property OpType As Nullable(Of Integer)

    Public Overridable Property Errors As ObservableListSource(Of [Error]) = New ObservableListSource(Of [Error])
    Public Overridable Property Items As ObservableListSource(Of Item) = New ObservableListSource(Of Item)
    Public Overridable Property OrderDetails As ObservableListSource(Of OrderDetail) = New ObservableListSource(Of OrderDetail)
    Public Overridable Property Spare_Parts As Spare_Part

End Class
