'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class QuoteDetail
    Public Property ID As Integer
    Public Property QuoteID As Integer
    Public Property RowNo As Integer
    Public Property ItemID As Nullable(Of Integer)
    Public Property Description As String
    Public Property Unit As String
    Public Property Price As Nullable(Of Decimal)
    Public Property Quantity As Nullable(Of Decimal)
    Public Property LeadTime As Nullable(Of Date)
    Public Property DiscountFraction As Nullable(Of Decimal)

    Public Overridable Property Item As Item
    Public Overridable Property Quote As Quote
    Public Overridable Property QuoteItemDetails As ICollection(Of QuoteItemDetail) = New HashSet(Of QuoteItemDetail)

End Class
